inherit_gem:
  simplycop:
    - .simplycop.yml
    - .simplycop_performance.yml

AllCops:
  TargetRubyVersion: 3.1

Metrics/BlockLength:
  Max: 250
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 25
