name: Create GitHub Release

on:
  push:
    branches:
      - "master"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Get Ruby Version
        id: get-ruby-version
        run: echo "::set-output name=RUBY_VERSION::$(bundle exec ruby -e 'puts Twiglet::VERSION')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.get-ruby-version.outputs.RUBY_VERSION }}
