name: Deploy Ruby Gem

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    strategy:
      matrix:
        ruby-version: [3.1, 3.2, 3.3, 3.4]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test

  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # Required for OIDC token

    needs: test
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: rubygems/release-gem@v1
      - name: Get Gem Version
        id: get-gem-version
        run: echo "GEM_VERSION=$(bundle exec ruby -e 'puts Twiglet::VERSION')" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: actions/github-script@v8
        env:
          GEM_VERSION: ${{ steps.get-gem-version.outputs.GEM_VERSION }}
        with:
          result-encoding: string
          script: |
            const { GEM_VERSION } = process.env
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: GEM_VERSION,
              generate_release_notes: true,
            })
