name: "version update action"
on:
  issue_comment:
    types: [created]
jobs:
  pr_commented:
    runs-on: ubuntu-20.04
    if: startsWith(github.event.comment.body, '/dobby')

    steps:
      - name: 'bump version'
        uses: simplybusiness/dobby@v2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_FILE_PATH: lib/twiglet/version.rb
